from fm_review.xhtml_sanitizer import sanitize_xhtml


def test_sanitize_clean_body():
    body = "<p>Clean content</p>"
    result, warnings = sanitize_xhtml(body)
    assert result == body
    assert not warnings

def test_sanitize_forbidden_tags():
    body = "<script>alert(1)</script><p>Text</p><iframe src='foo'></iframe>"
    result, warnings = sanitize_xhtml(body)
    assert "script" not in result
    assert "iframe" not in result
    assert "<p>Text</p>" in result
    assert any("Removed forbidden tags:" in w for w in warnings)

def test_sanitize_event_handlers():
    body = "<p onclick=\"alert('XSS')\">Text</p>"
    result, warnings = sanitize_xhtml(body)
    assert "onclick" not in result
    assert "<p>Text</p>" in result
    assert any("Removed 1 event handler(s)" in w for w in warnings)

def test_sanitize_js_urls():
    body = "<a href='javascript:alert(1)'>Link</a>"
    result, warnings = sanitize_xhtml(body)
    assert 'href=""' in result
    assert any("Removed javascript: URL(s)" in w for w in warnings)

def test_sanitize_unsafe_data_urls():
    body = "<a href='data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg=='>Link</a>"
    result, warnings = sanitize_xhtml(body)
    assert 'href=""' in result
    assert any("Removed unsafe data: URL(s)" in w for w in warnings)

def test_sanitize_safe_data_urls():
    body = "<img src='data:image/png;base64,iVBORw0KGgo='/>"
    result, warnings = sanitize_xhtml(body)
    assert 'data:image/png' in result
    assert not any("Removed unsafe data" in w for w in warnings)

def test_sanitize_ai_mentions():
    body = "<p>This was generated by AI and Agent 7</p>"
    result, warnings = sanitize_xhtml(body)
    assert result == body
    assert any("AI/Agent mentions detected" in w for w in warnings)

def test_sanitize_blue_header():
    body = '<th style="color: rgb(59, 115, 175)">Header</th>'
    result, warnings = sanitize_xhtml(body)
    assert result == body
    assert any("Prohibited blue header color" in w for w in warnings)
    assert not any("well-formedness" in w for w in warnings)

def test_sanitize_unknown_macros():
    body = '<ac:structured-macro ac:name="unknown-macro"></ac:structured-macro>'
    result, warnings = sanitize_xhtml(body)
    assert result == body
    assert any("Unknown Confluence macros: unknown-macro" in w for w in warnings)

def test_sanitize_allowed_macros():
    body = '<ac:structured-macro ac:name="warning"></ac:structured-macro>'
    result, warnings = sanitize_xhtml(body)
    assert result == body
    assert not warnings


def test_sanitize_wellformed_xhtml():
    """Well-formed XHTML produces no well-formedness warnings."""
    body = "<p>Valid <strong>content</strong></p>"
    result, warnings = sanitize_xhtml(body)
    assert not warnings


def test_sanitize_unclosed_tags():
    """HIGH-A4: unclosed tags produce a well-formedness warning."""
    body = "<p>Unclosed <strong>tag</p>"
    result, warnings = sanitize_xhtml(body)
    assert any("well-formedness" in w.lower() for w in warnings)
