import pytest
from fm_review.xhtml_sanitizer import sanitize_xhtml

def test_sanitize_clean_body():
    body = "<p>Clean content</p>"
    result, warnings = sanitize_xhtml(body)
    assert result == body
    assert not warnings

def test_sanitize_forbidden_tags():
    body = "<script>alert(1)</script><p>Text</p><iframe src='foo'></iframe>"
    result, warnings = sanitize_xhtml(body)
    assert "script" not in result
    assert "iframe" not in result
    assert "<p>Text</p>" in result
    assert len(warnings) == 1
    assert "Removed forbidden tags:" in warnings[0]

def test_sanitize_event_handlers():
    body = "<p onclick=\"alert('XSS')\">Text</p>"
    result, warnings = sanitize_xhtml(body)
    assert "onclick" not in result
    assert "<p>Text</p>" in result
    assert len(warnings) == 1
    assert "Removed 1 event handler(s)" in warnings[0]

def test_sanitize_js_urls():
    body = "<a href='javascript:alert(1)'>Link</a>"
    result, warnings = sanitize_xhtml(body)
    assert 'href=""' in result
    assert len(warnings) == 1
    assert "Removed javascript: URL(s)" in warnings[0]

def test_sanitize_unsafe_data_urls():
    body = "<a href='data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg=='>Link</a>"
    result, warnings = sanitize_xhtml(body)
    assert 'href=""' in result
    assert len(warnings) == 1
    assert "Removed unsafe data: URL(s)" in warnings[0]

def test_sanitize_safe_data_urls():
    body = "<img src='data:image/png;base64,iVBORw0KGgo='/>"
    result, warnings = sanitize_xhtml(body)
    assert 'data:image/png' in result
    assert not any("Removed unsafe data" in w for w in warnings)

def test_sanitize_ai_mentions():
    body = "<p>This was generated by AI and Agent 7</p>"
    result, warnings = sanitize_xhtml(body)
    assert result == body
    assert len(warnings) == 1
    assert "AI/Agent mentions detected" in warnings[0]

def test_sanitize_blue_header():
    body = "<th style='color: rgb(59, 115, 175)'>Header</th>"
    result, warnings = sanitize_xhtml(body)
    assert result == body
    assert len(warnings) == 1
    assert "Prohibited blue header color" in warnings[0]

def test_sanitize_unknown_macros():
    body = '<ac:structured-macro ac:name="unknown-macro"></ac:structured-macro>'
    result, warnings = sanitize_xhtml(body)
    assert result == body
    assert len(warnings) == 1
    assert "Unknown Confluence macros: unknown-macro" in warnings[0]

def test_sanitize_allowed_macros():
    body = '<ac:structured-macro ac:name="warning"></ac:structured-macro>'
    result, warnings = sanitize_xhtml(body)
    assert result == body
    assert not warnings
